### ISSUE TITLE
pnpm install  401

### ISSUE THREAD

**Issue by kcxg** [xuwei95/ezdata_frontend#1]
##### 版本号：
 master 分支

##### 问题描述：
pnpm install  报错，是不是因为私有仓库的原因

##### 截图&代码：
![image](https://github.com/xuwei95/ezdata_frontend/assets/31840413/de476337-6b9e-48eb-9b28-a6b0b4a8a05f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by xuwei95** [comment]
没用到私有仓库，已升级同步最新antd，可以再试下
