### ISSUE TITLE
dockerfile构建镜像失败，无dist目录

### ISSUE THREAD

**Issue by ConleyKong** [xuwei95/ezdata_frontend#2]
##### 版本号：
1.0.4

##### 问题描述：
希望类似ezdata一样通过docker方式直接启动，但是直接使用Dockerfile构建镜像时提示没有dist目录，想问下大佬这个前端项目是否未来计划支持直接docker启动的方式或者并入到ezdata的docker-compose内

##### 截图&代码：
docker build --squash  -f Dockerfile  -t ez-front .

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by xuwei95** [comment]
https://github.com/xuwei95/ezdata/blob/master/deploy/docker/docker-compose.yml  其中有前端镜像 ezdata123/ezdata-web:latest 可直接使用
